### ISSUE TITLE
state of repo

### ISSUE THREAD

**Issue by joefalso** [supercollider/learn#11]
hi, is this repo still functioning?

**Comment by smrg-lm** [comment]
Yes, why?

**Comment by joefalso** [comment]
Because I want to participate. Not right now though, first I'm gonna study
a bit more and prepare some material in Spanish. Thanks for answering.

**Comment by smrg-lm** [comment]
Because your user name I thought you might be a troll, something that's happening sadly often,  then I step out of the conversation. This repo is here not alive nor dead, depends on your observation. If you ever want to make a contribution you can do a pull request or discuss it in the scsynth.org forum.

**Comment by joefalso** [comment]
Thanks!, I'm no troll XD.

**Comment by smrg-lm** [comment]
Oki

**Comment by don-smith** [comment]
Looks like this issue is resolved?

**Comment by joefalso** [comment]
yes, someone reached me
